name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          bundle install
          yarn install

      - name: Build
        run: |
          bundle exec rake assets:precompile
          bundle exec rake assets:clean

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages 